folio:
  okapi:
    url: http://localhost:9130
  tenant:
    name: diku
    username: diku_admin
    password: admin
    validation:
      enabled: true
server:
  port: 8081
logging:
  level:
    liquibase: debug
spring:
  application:
    name: mod-data-export-spring
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: true
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: jobExecutionUpdateCG
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        interceptor:
          classes: org.folio.des.config.OkapiProducerInterceptor
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_empty
  datasource:
    username: folio_admin
    password: folio_admin
    url: jdbc:postgresql://localhost:5433/okapi_modules
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace,liquibase
