openapi: 3.0.0
info:
  title: Data Export Spring Configurations
  version: v1
servers:
  - url: /data-export-spring/
paths:
  /configs:
    get:
      description: Get a list of data export configurations
      operationId: getExportConfigs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/exportConfigCollection"
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
    post:
      description: Add an export configuration
      operationId: postExportConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/exportConfig"
        required: true
      responses:
        '201':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: good
        '400':
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /configs/{id}:
    put:
      description: Change an export configuration
      operationId: putExportConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/exportConfig"
        required: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Ok
        '400':
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '404':
          description: Export config not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
components:
  schemas:
    exportConfig:
      $ref: 'schemas/exportConfig.json#/ExportConfig'
    exportConfigCollection:
      $ref: 'schemas/exportConfigCollection.json#/ExportConfigCollection'
    errors:
      $ref: 'schemas/common/errors.json#/Errors'
  examples:
    errors:
      value:
        $ref: 'examples/errors.sample'
