openapi: 3.0.0
info:
  title: Data Export Spring Configurations
  version: v1
servers:
  - url: /data-export-spring/
paths:
  /configs:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/exportConfigCollection"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Get a list of data export configurations
      operationId: getExportConfigs
    post:
      responses:
        '201':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: good
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Add an export configuration
      operationId: postExportConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/exportConfig"
        required: true
  /configs/{id}:
    put:
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Ok
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '404':
          description: Export config not found
          content:
            text/plain:
              schema:
                type: string
                example: Rule not found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Change an export configuration
      operationId: putExportConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/exportConfig"
        required: true
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    exportConfig:
      $ref: 'schemas/exportConfig.json#/ExportConfig'
    exportConfigCollection:
      $ref: 'schemas/exportConfigCollection.json#/ExportConfigCollection'
